### PR TITLE
Change ignoreBrackets default, update preferences formatting and README

### PR DESCRIPTION
**Pull request by shanrauf**
Changes:
1. Updated README to correct typos and include Anki 2.1 installation instructions
2. Removed another unused import statement
3. Cleaned up the formatting of preferencesDialog.py so that code would not go off the page
4. Changed the default of "Ignore everything contained within brackets" to unchecked (This was set to default on because we were originally editting Morphman's code personally to share with people who use the MIA Japanese Support addon. However, now that this is on AnkiWeb, it should not be on by default because people use Morphman for other languages, and some people who study Japanese do not use the MIA Japanese Support addon; in both cases, they would not even know that this option was checked on by default)

### CODE REVIEW

**Comment by shanrauf** [comment]
New commit makes changing the column view a bit more smooth. Before, if you checked 1col instead of 4col for example, the view would not actually update until you re-selected a db view (like A, B-A, etc). Now, checking either 1col or 4col immediately updates the display.

**Comment by shanrauf** [comment]
Had an epiphany and commited another feature - batch adaptive subs (previously, you could only process one subtitle file at a time). Things you may want to change to your personal likings are how I saved the output files. To function, adaptiveSubs.py needs a subtitle file name to write to such as `folder/outputHere.ass`. I formatted files to be named `folder/fileNumber nameOfOriginalFile.ass`, but it can be changed to what you prefer if that is not ideal. 

Another thing that could be done is moving the logic of creating that formattedFileName from manager.py to adaptiveSubs.py, which is what I originally had, except that then you cannot add the fileNumber into the outputFilePath name because I get that number via the for loop in manager.py that I use to process every user-selected subtitle file. Thanks!

**Comment by landonepps** [comment]
Sorry for the late response. I took some time to think about the brackets.

It probably doesn't do any harm turned on by default, since other than Japanese, there probably aren't any sentences that have square brackets in them. But for Japanese, they're used to add additional pronunciation information, and the contents should be ignored. This is actually an Anki feature and doesn't have anything to do with the Japanese support addons. Even with no addons, if you make a field like `{{furigana:Reading}}`, it'll take the contents of the brackets and put them above the word as ruby text.

That being said, it could still lead to unexpected behavior if the user isn't studying Japanese, and doesn't know it's enabled.

I think the real solution is to have it enabled when the Morphemizer is set to "Japanese" and maybe "CJK", and have it disabled when it's set to "language with spaces".

**Comment by shanrauf** [comment]
@landonepps I understand what you are saying. Let me know what you think of this, and if you disagree, then let's go with what you said: When most people study Japanese, they have an "Expression" field (with the pure sentence), and a "Reading" field (with a duplicate of the sentence, but with the furigana brackets; this field is usually displayed on the back of the card while the plain Expression is on the front). Most people therefore have their Morphman process the expression field of their cards, not the reading fields of their cards. So since most people use Morphman w the expression field, then even if this is rare, it could be possible that people have crucial information inside of their brackets on the expression field, but having that setting on by default would ignore those potentially crucial morphs. (I can't think of an example to be honest, but I think there might be more harm in that setting being on by default without people knowing then having the setting off by default without people knowing) What do you think?

**Comment by landonepps** [comment]
In my old decks, I would put furigana in the "Expression" field if it was an uncommon reading.
For example, I want the pronunciation of `今日[こんにち]` (konnichi - nowadays) always displayed because otherwise, I'd read it as `今日[きょう]` (kyou - today), which is the standard pronunciation.

I don't think people studying Japanese would put brackets around regular words in the expression field. Especially because the half-width square brackets [] aren't used in Japanese. When writing Japanese, I'd use one of these instead:「」【】［］〈〉

Also, as you said, the Reading field is usually a duplicate of the Expression field with added furigana in brackets. If you use brackets in the Expression field, they will be copied to the Reading field, and Anki will think it should be placed over the preceding word as furigana.

image

image

**Comment by shanrauf** [comment]
@landonepps You're 100% right, I totally forgot that people do this. My Japanese isn't at a level where I do this frequently enough so I forgot. Let's go with what you were saying then. Should you create a Github issue for having brackets be ignored always when Japanese/CJK is checked as the Morphemizer, but not ignored when it's not Japanese/CJK?

**Comment by landonepps** [comment]
I already created the issue here: #9. 

I agree with you that people should be able to disable it, even though I can't see why someone studying Japanese would use brackets in the expression field for anything other than furigana.

I think the setting should default to true and only affect Japanese decks. I explained it in more detail in the issue description.

**Pull request merged**
