### PR TITLE
Add Chinese support using Jieba

### PR DESCRIPTION
**Pull request by shanrauf**
Resolves issue #10. The CJK parser only parsers individual characters, not necessarily words, so I added support for the Jieba morphemizer parser, which was originally used in the 2.0 version of Morphman from [this repository](https://github.com/NinKenDo64/Jieba-Morph). Let me know if you find any issues @landonepps

### CODE REVIEW

**Comment by shanrauf** [comment]
The second commit is just me downloading Jieba directly for the [Jieba repository](https://github.com/fxsjy/jieba), as opposed to grabbing it directly from the old version of the [Morphman addon](https://github.com/NinKenDo64/Jieba-Morph).

**Comment by landonepps** [comment]
Is there any reason to leave the CJK parser?
I think the Readme is wrong, and it's probably still needed for Korean. Korean has spaces, but it also has particles that attach to the end of words.

If that's the case, we should probably rename CJK to Korean. Since Chinese would use the Jieba parser, and Japanese uses MeCab, which is installed with the Japanese Support addon.

**Comment by shanrauf** [comment]
I don't know too much about Korean, but I tested teh CJK morphemizer with a bunch of premade Korean decks that I have and it does not work at all (whereas language with spaces morphemizer works fine). 

The only use the CJK parser could probably be used (and I considered doing this but changed my mind) is for Japanese or Chinese characters; you would use the database manager and extract morphemes from a list of kanji/characters using the CJK parser, and then you would use the mass tagger feature in the browser to tag all the cards that contain those characters you want to study. But it's a bit of a hassle, and it's not a good idea to use both the CJK parser and Japanese/Chinese parser at the same time on one profile anyway. I'd say it isn't necessary at all, but I might not know enough.

**Comment by landonepps** [comment]
I looked a bit more into it, and it only supports pinyin, hanzi, and zhuyin. I didn't realize that it was only for parsing individual characters. Since it has a totally different use case, we should probably leave it alone.

**Pull request merged**
